import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ThemeProvider } from "./providers/ThemeProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ThemeProvider>
            <GoogleOAuthProvider clientId="452754564019-jvte6b9lnpo36p087trg19cs672g3m0r.apps.googleusercontent.com">
              {children}
            </GoogleOAuthProvider>
          </ThemeProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
